language: cpp
sudo: true
dist: trusty
matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang50
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env: COMPILER='clang++-5.0' BUILD_TYPE='Release'

    - os: linux
      compiler: clang
      addons: *clang50
      env: COMPILER='clang++-5.0' BUILD_TYPE='Debug'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Release'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'

install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    sudo apt-get -qq update
    sudo apt-get -y -qq --allow-unauthenticated install llvm-5.0 libgc-dev exuberant-ctags build-essential libc++-dev libclang-5.0-dev libclang1-5.0 libllvm5.0 llvm-5.0-dev libedit-dev libz-dev llvm-5.0-runtime
    wget -q https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz
    tar xf boost_1_62_0.tar.gz
    cd boost_1_62_0/
    ./bootstrap.sh
    sudo ./b2 install --with-filesystem -j"$(nproc)"
    mkdir -p ${DEPS_DIR}/cmake && cd $_
    CMAKE_FILE="cmake-3.8.2-Linux-x86_64"
    wget --no-check-certificate --quiet -O - http://www.cmake.org/files/v3.8/${CMAKE_FILE}.tar.gz
    tar xf ${CMAKE_FILE}.tar.gz
    test -f ${CMAKE_FILE}/bin/cmake
    export PATH=${DEPS_DIR}/cmake/${CMAKE_FILE}/bin:${PATH}
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew list cmake || brew install cmake
    brew list ctags || brew install ctags
    brew list boost || brew install boost
    brew list llvm || brew install llvm
    brew list bdw-gc || brew install bdw-gc
  fi
before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . -DFORMAT_BEFORE_BUILD=OFF -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
script:
    - make -j"$(nproc)"
    - make test
