language: cpp
sudo: true
dist: trusty
compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - build-essential
    - clang-5.0
    - libclang-5.0-dev
    - libclang1-5.0
    - libstdc++6
    - libstdc++-6-dev
    - llvm-5.0
    - libllvm5.0
    - llvm-5.0-dev
    - libgc-dev
    - exuberant-ctags
    - libedit-dev
    - libz-dev
matrix:
  include:
  - os: linux
    env: COMPILER='clang++-5.0' BUILD_TYPE='Release'
  - os: linux
    env: COMPILER='clang++-5.0' BUILD_TYPE='Debug'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Release'
  - os: osx
    env: COMPILER='clang++' BUILD_TYPE='Debug'
install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    wget -q https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz
    tar xf boost_1_62_0.tar.gz
    cd boost_1_62_0/
    ./bootstrap.sh
    sudo ./b2 install --with-filesystem -j"$(nproc)" -d0
    mkdir -p ${TRAVIS_BUILD_DIR}/cmake && cd $_
    CMAKE_FILE="cmake-3.8.2-Linux-x86_64"
    wget --no-check-certificate --quiet http://www.cmake.org/files/v3.8/${CMAKE_FILE}.tar.gz
    tar xf ${CMAKE_FILE}.tar.gz
    test -f ${CMAKE_FILE}/bin/cmake
    export PATH=${TRAVIS_BUILD_DIR}/cmake/${CMAKE_FILE}/bin:${PATH}
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew list cmake || brew install cmake
    brew list ctags || brew install ctags
    brew list boost || brew install boost
    brew list llvm || brew install llvm
    brew list bdw-gc || brew install bdw-gc
  fi
before_script:
- cd ${TRAVIS_BUILD_DIR}
- cmake . -DFORMAT_BEFORE_BUILD=OFF -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
script:
- make -j"$(nproc)"
- make test
after_success:
- make package
before_deploy:
- cd dist
deploy:
  provider: s3
  bucket: scopion-latest
  access_key_id: AKIAINAG7HV7Z4TPIRLA
  secret_access_key:
    secure: X7lY+2RDkS2Yf0lfYVgeI6o+KvRu3U7ZLxSudhIKo/6YOurmexAJ4cUwBWB3GllcAUfICDkMqYJu0aWkM2nWVVNXEVuIVUF7Q8Pb64vkcM+SnsIA1Jw89XHtECW26/pjBGkAN5K5LTO7cF6+jp6TB1txRhfNVwJTh+rSi4D/WCMsWFE266koGTyutCKvhy+to9pXDNM+pPl/7yukP0VPkjTjTTu7/fEHoGbYh/9dvtNKhs1kwG1VC8UEEAM9y0SDhR+yWl/ZAMZB39Yn0Y91Uks/Ev55m6leTKO0f3Tbof7ajoooOCbuy8hkB0U2uBK7qhqP7pNX+bsuKhYaWmEPJJzex4F6dgWjHPtbJuvS6MaoVHuTzRSK2H6NvKeh4crr+9JrymXKmFV1ezTbLpie41w80K2We+IKFTS5QO8NzbcYSsLwJnyDaLbat6k+PgNF4SofUeeXJ2cEgx+2MTn0u9Bg2KZXVEqvkc9o1Nhv2KmI1F0tf2NxYXjOSOzoGeFIPSyQvMOYP1dfNLpK0awwAL81oRhJMbnHQ6IHrAnaNy8VNqjgEOsLOa0CBuk3UD83S9g/fdJfqiaCzUoEdEUjujAuwbQDCnkCvz1mC4+lh1wsSNuQUfnQj0MqmKIiDclLoVZQ11JBrvoXAIPv1TMN27sOcV0jZjDBJb2IClgBy8Y=
  skip_cleanup: true
  upload-dir: "$TRAVIS_BRANCH"
  on:
    all_branches: true
